adapters: 
  - http
  - ws
debug: true
enableVerify: true
verifyKey: keyofMiraiHttpAPI
singleMode: true
cacheSize: 8192
adapterSettings:
  http:
    host: localhost
    port: 4201
    cors: [*]
  ws:
    host: localhost
    port: 4201
    reservedSyncId: -1
